global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'producer'
    metrics_path: '/health'
    static_configs:
      - targets: ['producer:5000']

  - job_name: 'consumer'
    metrics_path: '/health'
    static_configs:
      - targets: ['consumer:5000']
